### ISSUE TITLE
frankenstyle naming violations

### ISSUE THREAD

**Issue by danmarsden** [Advacheck-OU/moodle-plagiarism_advacheck#3]
Please fix your function names in localib.php and check other classes and functions to make sure they follow our frankenstyle naming conventions.
https://moodledev.io/general/development/policies/codingstyle/frankenstyle

note this is a blocker for plugins db approval.

**Comment by danmarsden** [comment]
another good example - the class name "plagiarism_setup_form" is not correct on it's own - it should be namespaced or prefixed with the frankenstyle name.

**Comment by danmarsden** [comment]
..also look at the constant naming rules - most of the ones in your constants.php file are incorrect.

**Comment by SimonBrigadier** [comment]
Changed the names of functions and constants in accordance with the documentation.
