### ISSUE TITLE
Please review use of PARAM_RAW

### ISSUE THREAD

**Issue by danmarsden** [Advacheck-OU/moodle-plagiarism_advacheck#4]
I see a lot of PARAM_RAW usage that is incorrect - and areas where it's hard to tell if it's used directly within SQL as well - please review all your PARAM_RAW calls and ensure they are appropriately sanitised where possible.

this is a blocker for plugins db approval.

**Comment by SimonBrigadier** [comment]
Changed the PARAM_RАW to the appropriate parameters.
