### ISSUE TITLE
missing login and capability checks

### ISSUE THREAD

**Issue by danmarsden** [Advacheck-OU/moodle-plagiarism_advacheck#5]
please see: https://moodledev.io/general/development/policies/security#summary-of-the-guidelines

in particular ajax.php and downloadfile.php look incorrect.

for example - is it intentinoal that any user can access any file from the downloadfile.php page? - including files that don't belong to them or from courses they should not have access to?

this is a blocker for plugins db approval.

**Comment by SimonBrigadier** [comment]
Add confirm_sesskey() and require_course_login() on pages.
