### ISSUE TITLE
Invalid lang string file.

### ISSUE THREAD

**Issue by danmarsden** [Advacheck-OU/moodle-plagiarism_advacheck#7]
string concatenation in the lang packs is not allowed - it causes problems for the Moodle translation tool - you should not treat this file as working like a normal PHP file.

eg:
$string['test'] = "sometext"."somemoretext";
or
$string['test'] = "sometext".$string['someotheritem'];

each string must be contained within one set of quotes eg:
$string['test'] = "sometext somemoretext"; 

note this is a blocker for plugins db approval.

**Comment by SimonBrigadier** [comment]
String concatenation was removed from the language pack.
