### ISSUE TITLE
please review sql queries and use correct placeholders

### ISSUE THREAD

**Issue by danmarsden** [Advacheck-OU/moodle-plagiarism_advacheck#9]
When you must use custom SQL code, use place-holders to insert values into the queries - this is a security requirement and a blocker for plugins db approval.

please review your SQL queries and ensure you are using placeholders correctly as per:
https://moodledev.io/general/development/policies/security/sql-injection

here are some examples in your code that need to be fixed (there are others as well.)
https://github.com/Advacheck-OU/moodle-plagiarism_advacheck/blob/main/advacheck/lib.php#L62
https://github.com/Advacheck-OU/moodle-plagiarism_advacheck/blob/main/advacheck/lib.php#L82
https://github.com/Advacheck-OU/moodle-plagiarism_advacheck/blob/main/advacheck/lib.php#L945
https://github.com/Advacheck-OU/moodle-plagiarism_advacheck/blob/main/advacheck/lib.php#L958

**Comment by SimonBrigadier** [comment]
String concatenation was removed from sql queries.
